name: Run tests on macOS
on:
  push:
  workflow_dispatch:

jobs:
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Swift test
        run: swift test
